services:
  redis: # 서비스 이름
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes: # 데이터 영구 저장 설정
      - redis-data:/data
    command: redis-server --appendonly yes # 실행 명령 - 데이터 변경시 디스크에 로그 낭김

volumes: # 볼륨 설정
  redis-data: