version: '3'
services:
  db:
    image: postgres:17
    container_name: discodeit-db
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: discodeit_db
      TZ: Asia/Seoul
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - binary_content_data:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    # 미리 이미지 빌드 필요: docker build -t discodeit:local .
    image: discodeit:local
    container_name: discodeit
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  binary_content_data:

