# - build는 앱을 패키징하는 작업이므로 환경변수가 없어도 문제 없음.
# - run은 실제로 앱을 실행하는 작업이므로 환경변수가 반드시 필요
# 내부 환경변수 주입 -> ide
# 외부 환경변수 주입 -> 터미널, 배포서버

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: discodeit
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 50MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.5.5
    ddl-auto: validate
    storage:
      type: local
      root-path: .discodeit/storage
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: health,loggers,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

discodeit:
  storage:
    type: local
    root-path: .discodeit/storage
