spring:
  application:
    name: discodeit
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.5.5

management:
  endpoints:
    web:
      exposure:
        include: health,loggers,info,metrics
  info:
    env:
      enabled: true

discodeit:
  storage:
    type: local
    root-path: /binary-data
