spring:
  application:
    name: discodeit

  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # (create, create-drop, update, validate 등 사용 가능)
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  cache:
    type: redis # caffeine | redis
    cache-names:
      - channels
      - notifications
      - users
    caffeine:
      spec: >
        maximumSize=100,
        expireAfterAccess=600s,
        recordStats
      # 캐시에 담을 객체 수, 자동 삭제, 통계정보 기록
    redis:
      enable-statistics: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: localhost:9092 # 애플리케이션이 Kafka 접속시 쓸 주소
    producer:
      # Kafka는 바이트 형태로만 데이터를 주고받음. 이하는 직렬화 설정임.
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: discodeit-group # 애플리케이션이 속한 소비자 그룹
      auto-offset-reset: earliest
        # 어디서부터 메시지를 읽기 시작할지 설정.
        # earliest: 처음부터, latest: 지금 시점 이후부터
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
    root: info
    org.hibernate.SQL: debug # JDBC 관련 로그를 DEBUG 레벨로 출력
    # SQL 파라미터를 출력
    org.hibernate.orm.jdbc.bind: info

discodeit:
  storage:
    type: ${STORAGE_TYPE:local} # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:uploads}
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)
  setup:
    admin:
      email: "${ADMIN_EMAIL:admin@discodeit.com}" # TODO 기본값 .env로 이동
      username: "${ADMIN_USERNAME:admin}"
      password: "${ADMIN_PASSWORD:admin1234}"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers"
  endpoint:
    health:
      show-details: always
    caches:
      access: unrestricted
    metrics:
      export:
        simple:
          enabled: true
  observations:
    annotations:
      enabled: true

info:
  application:
    name: "Discodeit"
    version: 1.7.0

  environment:
    java-version: "17"
    spring-boot-version: "3.4.0"

    settings:
      datasource:
        url: "${spring.datasource.url}"
        driver: "${spring.datasource.driver-class-name}"
      jpa:
        ddl-auto: "${spring.jpa.hibernate.ddl-auto}"
      storage:
        type: "${discodeit.storage.type}"
        path: "${discodeit.storage.path}"
      multipart:
        max-file-size: "${spring.servlet.multipart.max-file-size}"
        max-request-size: "${spring.servlet.multipart.max-request-size}"

  author:
    name: "Discodeit"


jwt:
  secret: "nimbus-jose-jwt-practice-secret-key-must-be-at-least-256-bits"
  issuer: "discodeit-server"
  access-token-validity-in-ms: 1800000
  refresh-token-validity-in-ms: 1209600000
