discodeit:
  storage:
    type: local
    local:
      root-path: C:\\spring\\codeit-bootcamp-spring\\6-sprint-mission\\src\\main\\resources\\data\\files\\
spring:
  application:
    name: discodeit
  cache:
    type: caffeine
    caffeine:
      spec:
        recordStats
  config:
    import: optional:file:.env
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
code:
  repository:
    type: file
logging:
  level:
    root: INFO
security:
  key:
    remember-me: test-remember-me-key
  login: jwt

jwt:
  access-token:
    secret: test_access_token_secret
    expiration: 3600000
  refresh-token:
    secret: test_refresh_token_secret
    expiration: 86400000
  issuer: test_app_name