spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          name: discodeit
  application:
    name: discodeit

management:
  endpoints:
    web:
      base-path: /actuator  # 기본값이지만 명시적으로 선언
      exposure: # 노출할 Actuator 엔드포인트 설정 - 모두(*) | 필요한 엔드포인트만 (health, info 등)
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always # health 엔드포인트의 세부 정보 표시 설정

server:
  port: 9090