package com.sprint.mission.discodeit.enums;

public enum ErrorCode {

    // Auth
    INVALID_AUTH,
    ACCESS_DENIED,

    USER_NOT_FOUND,
    DUPLICATE_USER,

    CHANNEL_NOT_FOUND,
    PRIVATE_CHANNEL_UPDATE,
    DUPLICATE_CHANNEL,

    MESSAGE_NOT_FOUND,

    READ_STATUS_NOT_FOUND,
    DUPLICATE_READ_STATUS,

    BINARY_CONTENT_NOT_FOUND,
    DUPLICATE_BINARY_CONTENT,
    BINARY_CONTENT_UPLOAD_ALREADY_SUCCEEDED,

    NOTIFICATION_NOT_FOUND,

    VALIDATION_FAILED;
}
